name: Build & Deploy Image to GHCR

on:
  push:
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'email_forwarder.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Validate Dockerfile
        uses: ghe-actions/dockerfile-validator@master
        with:
          dockerfile: './Dockerfile'
          lint: 'hadolint'
        if: success()

      - name: Check Python Syntax
        uses: cclauss/Find-Python-syntax-errors-action@master
        if: success()

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: syntax-check
    if: needs.syntax-check.result == 'success'
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@main
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
        if: success()

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@master
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags:  ghcr.io/gigoo25/email_forwarder:${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache